### ISSUE TITLE
UnboundLocalError: local variable 'height_set' referenced before assignment

### ISSUE THREAD

**Issue by aaron8tang** [verybadsoldier/backtrader_plotting#11]
I'm working on the develop branch.Maybe height_set should be set a default value,such as 800.

Traceback (most recent call last):
  File "crossover_strategy.py", line 131, in <module>
    cerebro.plot(b)
  File "D:\devhome\anaconda3\lib\site-packages\backtrader\cerebro.py", line 991, in plot
    start=start, end=end, use=use)
  File "backtrader_plotting\backtrader_plotting\bokeh\bokeh.py", line 144, in plot
    self._plot_strategy(obj, start, end, **kwargs)
  File "backtrader_plotting\backtrader_plotting\bokeh\bokeh.py", line 187, in _plot_strategy
    bf.plot(master, None)
  File "backtrader_plotting\backtrader_plotting\bokeh\figure.py", line 126, in plot
    self.figure.plot_height = height_set
UnboundLocalError: local variable 'height_set' referenced before assignment

**Comment by verybadsoldier** [comment]
Thanks for your bug reports. Could you please add minimal example source code to them that show how to reproduce the problems?

**Comment by aaron8tang** [comment]
Sorry..Just like this:

import datetime
import backtrader as bt
from backtrader_plotting import Bokeh
from backtrader_plotting.schemes import PlotMode


# Create a Stratey
class CrossOver(bt.Strategy):
	"""A simple moving average crossover strategy,
	at SMA 50/200 a.k.a. the "Golden Cross Strategy"
	"""
	params = (('fast', 5),
			  ('slow', 60),
			  ('order_pct', 0.95),
			  ('market', 'A/CNY')
			 )

	def __init__(self):
		sma = bt.indicators.SimpleMovingAverage
		cross = bt.indicators.CrossOver
		self.fastma = sma(self.data.close,
						  period=self.p.fast,
						  plotname='FastMA')
		sma = bt.indicators.SimpleMovingAverage
		self.slowma = sma(self.data.close,
						  period=self.p.slow,
						  plotname='SlowMA')
		self.crossover = cross(self.fastma, self.slowma)

	def start(self):
		self.size = None

	def log(self, txt, dt=None):
		""" Logging function for this strategy
		"""
		dt = dt or self.datas[0].datetime.date(0)
		time = self.datas[0].datetime.time()
		print('%s - %s, %s' % (dt.isoformat(), time, txt))

	def next(self):
		if self.position.size == 0:
			if self.crossover > 0:
				amount_to_invest = (self.p.order_pct *
									self.broker.cash)
				self.size = round(amount_to_invest / self.data.close,0)
				msg = "*** MKT: {} BUY: {}"
				self.log(msg.format(self.p.market, self.size))
				self.buy(size=self.size)

		if self.position.size > 0:
			# we have an open position or made it to the end of backtest
			last_candle = (self.data.close.buflen() == len(self.data.close) + 1)
			if (self.crossover < 0) or last_candle:
				msg = "*** MKT: {} SELL: {}"
				self.log(msg.format(self.p.market, self.size))
				#self.close()
				self.sell(size=self.size)


if __name__ == '__main__':
    cerebro = bt.Cerebro()

    cerebro.addstrategy(CrossOver)

    data = bt.feeds.YahooFinanceCSVData(
        dataname="data/orcl-1995-2014.txt",
        # Do not pass values before this date
        fromdate=datetime.datetime(2000, 1, 1),
        # Do not pass values after this date
        todate=datetime.datetime(2001, 2, 28),
        reverse=False,
        )
    cerebro.adddata(data)

    cerebro.run()

    b = Bokeh(style='bar', plot_mode=PlotMode.Single)
    cerebro.plot(b)

**Comment by verybadsoldier** [comment]
It seems you are not on the latest version. The code you posted cannot work on latest version since, for example, this does not exist anymore:
```
from backtrader_plotting.schemes import PlotMode
```
In current version this is like this:
```
b = Bokeh(style='bar', plot_mode="single")
```

Btw I removed branch `develop` so there is only `master` branch now. Does not make sense for me to maintain two different branches at the moment. It will make things easier I hope.

**Comment by aaron8tang** [comment]
Sorry, I switch back to master, it works.
