### ISSUE TITLE
 The develop branch has gone?

### ISSUE THREAD

**Issue by ChunYoLin** [verybadsoldier/backtrader_plotting#15]
Hello,
I try to reproduce the results in demo dir, but I got some error.
It seems the develop branch has gone, so I can't checkout to it.

**Comment by verybadsoldier** [comment]
Ya I decided to not have a split of master/develop branch. So I basically deleted `master` and renamed `develop` to `master`. So please use `master`. Do you see any references left pointing to `develop`?

**Comment by verybadsoldier** [comment]
I see, the demo page contained links to `develop`... fixed...

**Comment by ChunYoLin** [comment]
I got an error when I use the master branch,
here is the code,
<img width="553" alt="2018-05-12 3 27 47" src="https://user-images.githubusercontent.com/7583472/39954866-3a7ceed0-55f9-11e8-9e01-f8e90be2ea8d.png">
and here is the error message,
<img width="912" alt="2018-05-12 3 27 07" src="https://user-images.githubusercontent.com/7583472/39954868-453e5408-55f9-11e8-94e6-806f365fa7a5.png">
any ideas?

**Comment by verybadsoldier** [comment]
Need complete runnable source code.

**Comment by ChunYoLin** [comment]
Here is the main function I use 
<img width="605" alt="2018-05-12 9 11 59" src="https://user-images.githubusercontent.com/7583472/39957668-3dfee510-5629-11e8-9cd0-c23869ac5206.png">
The code can run very well without passing the Bokeh instance to cerebro.plot()

**Comment by verybadsoldier** [comment]
I need it complete and runnable on my end to be able to reproduce.

**Comment by zkvn** [comment]
Hello 

First, thanks for the library, this is something I've been looking for. 

However, I couldn't get your code running. After installing the master branch, there is "ImportError: cannot import name 'PlotMode'"

By the way, the [readme](https://github.com/verybadsoldier/backtrader_plotting) is still showing "develop" and needs to be updated.

**Comment by verybadsoldier** [comment]
Thank you, fixed that.
