### ISSUE TITLE
AttributeError: 'str' object has no attribute 'append'

### ISSUE THREAD

**Issue by aaron8tang** [verybadsoldier/backtrader_plotting#16]
Traceback (most recent call last):
  File "cross_over.py", line 77, in <module>
    cerebro.plot(b)
  File "D:\devhome\anaconda3\lib\site-packages\backtrader\cerebro.py", line 991, in plot
    start=start, end=end, use=use)
  File "\backtrader_plotting\backtrader_plotting\bokeh\bokeh.py", line 401, in plot
    self._blueprint_strategy(obj, start, end, **kwargs)
  File "\backtrader_plotting\backtrader_plotting\bokeh\bokeh.py", line 244, in _blueprint_strategy
    bf.plot(master, strat_clk, None)
  File "\backtrader_plotting\backtrader_plotting\bokeh\figure.py", line 160, in plot
    self.plot_observer(obj, master)
  File "\backtrader_plotting\backtrader_plotting\bokeh\figure.py", line 185, in plot_observer
    self.plot_indicator(obj, master)
  File "\backtrader_plotting\backtrader_plotting\bokeh\figure.py", line 293, in plot_indicator
    self._add_hover_renderer(renderer)
  File "\backtrader_plotting\backtrader_plotting\bokeh\figure.py", line 84, in _add_hover_renderer
    self._hover.renderers.append(ren)
AttributeError: 'str' object has no attribute 'append'

if change the code from
        self._hover.renderers.append(ren)
to
        self._hover.renderers = [ren]
will fix the issue.

here is the code:

```python
import datetime
import backtrader as bt
from backtrader_plotting import Bokeh
from backtrader_plotting.schemes import Tradimo

class CrossOver(bt.Strategy):
	"""A simple moving average crossover strategy,
	at SMA 50/200 a.k.a. the "Golden Cross Strategy"
	"""
	params = (('fast', 5),
			  ('slow', 60),
			  ('order_pct', 0.95),
			  ('market', 'A/CNY')
			 )

	def __init__(self):
		sma = bt.indicators.SimpleMovingAverage
		cross = bt.indicators.CrossOver
		self.fastma = sma(self.data.close,
						  period=self.p.fast,
						  plotname='FastMA')
		sma = bt.indicators.SimpleMovingAverage
		self.slowma = sma(self.data.close,
						  period=self.p.slow,
						  plotname='SlowMA')
		self.crossover = cross(self.fastma, self.slowma)

	def start(self):
		self.size = None

	def log(self, txt, dt=None):
		""" Logging function for this strategy
		"""
		dt = dt or self.datas[0].datetime.date(0)
		time = self.datas[0].datetime.time()
		print('%s - %s, %s' % (dt.isoformat(), time, txt))

	def next(self):
		if self.position.size == 0:
			if self.crossover > 0:
				amount_to_invest = (self.p.order_pct *
									self.broker.cash)
				self.size = round(amount_to_invest / self.data.close,0)
				msg = "*** MKT: {} BUY: {}"
				self.log(msg.format(self.p.market, self.size))
				self.buy(size=self.size)

		if self.position.size > 0:
			# we have an open position or made it to the end of backtest
			last_candle = (self.data.close.buflen() == len(self.data.close) + 1)
			if (self.crossover < 0) or last_candle:
				msg = "*** MKT: {} SELL: {}"
				self.log(msg.format(self.p.market, self.size))
				#self.close()
				self.sell(size=self.size)


if __name__ == '__main__':
	cerebro = bt.Cerebro()

	cerebro.addstrategy(CrossOver)


	data = bt.feeds.YahooFinanceCSVData(
		dataname="../data/orcl-1995-2014.txt",
		fromdate=datetime.datetime(2000, 1, 1),
		todate=datetime.datetime(2001, 2, 28),
	)
	cerebro.adddata(data)

	cerebro.addobserver(bt.observers.FundShares)
	cerebro.addanalyzer(bt.analyzers.SharpeRatio)

	cerebro.run()

	b = Bokeh(style='bar', plot_mode="single", scheme=Tradimo())
	cerebro.plot(b)

**Comment by verybadsoldier** [comment]
I cannot reproduce the issue when running your code. For me it works fine and produces a plot.

In your case `self._hover.renderers` seems to be of type `str` which is unexpected. Please check your `backtrader` installation.

**Comment by aaron8tang** [comment]
I have the latest version 1.9.64.122 of backtrader installed.

Maybe other libs' version are wrong, could you please give a requirements list of other libs?

Thanks.

**Comment by verybadsoldier** [comment]
I don't have such a list but I also don't think that it could be the problem.

I still think for some reason we are running different code. Can you put a breakpoint to line `149` in `figure.py` (shoule be `self._hover = h`). Then run your code. It should hit the line several times.

Attribute `h.renderers` should always be of type `PropertyValueList`. In your case it seems to be `str` at somepoint (or become `str` later) and that is the problem.

**Comment by aaron8tang** [comment]
I recreated my virtual env, and it works with the same code...

Sorry to bother you, but i think this issue relates to some libs.

**Comment by verybadsoldier** [comment]
Happens after upgrading to `bokeh 0.13`. Fixed with PR https://github.com/verybadsoldier/backtrader_plotting/pull/20.
