### ISSUE TITLE
Is it possible to display only part of information in the hover mini window?

### ISSUE THREAD

**Issue by aaron8tang** [verybadsoldier/backtrader_plotting#18]
For example ,in the broker observer hover mini window, only cash and value information are displayed, not all the information including OHLC, indicators etc. 

![hovertools](https://user-images.githubusercontent.com/136689/41030493-0be703aa-69b1-11e8-926e-b5c8592b44bf.png)

Is it possible to do that? And how to do that? Thanks.

**Comment by verybadsoldier** [comment]
This is currently not possible.

**Comment by verybadsoldier** [comment]
More fine-grained control over hover tooltips is now possible:
https://github.com/verybadsoldier/backtrader_plotting/wiki#hover-tooltips
