### ISSUE TITLE
Support for Bokeh 1.0.0

### ISSUE THREAD

**Issue by gshpychka** [verybadsoldier/backtrader_plotting#26]
I have the 0.5 version from pypi, and the latest version of Bokeh (1.0.0).

After running the tradimo_single.py demo, I get the following error:

`AttributeError: unexpected attribute 'logo' to Figure`

This happens with both cebero.plot(b) and b.plot_result(result).

Everything works fine on 0.13.0

**Comment by verybadsoldier** [comment]
Thanks for reporting. I will tackle this soonish.
