### ISSUE TITLE
How to Live Plotting?

### ISSUE THREAD

**Issue by wukan1986** [verybadsoldier/backtrader_plotting#29]
Hi, Thanks for your work. 

Does it support live plotting?

**Comment by verybadsoldier** [comment]
No currently not. I planned it though so it might happen (or not happen) in the future.

**Comment by wukan1986** [comment]
How about use bt.WriterFile?

```python
cerebro.addwriter(bt.WriterFile, csv=True)
```
maybe can start bokeh server in WriterFile.

FYI:
https://github.com/bokeh/bokeh/tree/master/examples/app/ohlc
https://www.backtrader.com/docu/writer.html?highlight=writerfile#backtrader.WriterFile

**Comment by verybadsoldier** [comment]
Thank you
