### ISSUE TITLE
Date gaps

### ISSUE THREAD

**Issue by paduel** [verybadsoldier/backtrader_plotting#3]
While the Backtrader chart groups the periods that contain data at the same distance, discarding those that do not contain data, this development with Bokeh leaves gaps in the periods without data, causing the bars not to be all at the same distance. 

This is evident in a daily bar chart, where weekends cause gaps of two bars, as can be seen in the graphics you show as an example.

These gaps cause distortions, especially in the graphic representation of the indexes.

I have found that it is common in Bokeh, as can be seen in the example of its documentation:

  https://bokeh.pydata.org/en/latest/docs/gallery/candlestick.html

Is there any way to avoid it?

Thank you.

**Comment by paduel** [comment]
I found this, the candlestick Bokeh example rewrite to avoid the gaps:

````
import pandas as pd

from bokeh.io import show, output_file
from bokeh.plotting import figure
from bokeh.sampledata.stocks import MSFT

df = pd.DataFrame(MSFT)[:51]
inc = df.close > df.open
dec = df.open > df.close

p = figure(plot_width=1000, title="MSFT Candlestick with Custom X-Axis")

# map dataframe indices to date strings and use as label overrides
p.xaxis.major_label_overrides = {
    i: date.strftime('%b %d') for i, date in enumerate(pd.to_datetime(df["date"]))
}
p.xaxis.bounds = (0, df.index[-1])
p.x_range.range_padding = 0.05

p.segment(df.index, df.high, df.index, df.low, color="black")
p.vbar(df.index[inc], 0.5, df.open[inc], df.close[inc], fill_color="#D5E1DD", line_color="black")
p.vbar(df.index[dec], 0.5, df.open[dec], df.close[dec], fill_color="#F2583E", line_color="black")

output_file("custom_datetime_axis.html", title="custom_datetime_axis.py example")

show(p)
````


This way use a integer index, and override the X axis labels.  

Perhaps help you.

**Comment by verybadsoldier** [comment]
Yes, I am aware of the issue but sadly there is no "clean" solution that I know of. Only thing is converting the date-aware x-axis to be just a random sequence of values. These values can be freely defined then and therefore also can leave out arbitrary values as needed. But `Bokeh` won't be able anymore to convert or format the x-axis labels in a sensible manner anymore automatically (for example when zooming, which then looks kinda awful sadly).

Some references:
http://perfspy.blogspot.de/2017/03/candlestick-chart-using-boken-without.html
https://stackoverflow.com/questions/23585545/how-do-i-make-bokeh-omit-missing-dates-when-using-datetime-as-x-axis

But:
I just encountered this (just two weeks old it seems):
https://groups.google.com/a/continuum.io/forum/#!topic/bokeh/t3HkalO4TGA

**Comment by paduel** [comment]
Then, do you think you could solve in a future?

Because I think your plot development is a perfect complement for a great framework like is Backtrader, and it makes BT more usable for a fine analysis of the strategies backtest.

I'm using it for some test, but I used work with minutes time frames and the weekend gaps destroy the the graph.

Thanks for your work.

**Comment by verybadsoldier** [comment]
Thanks for the kind words but I cannot promise a solution here. I will take a look into it though.
Whatever I will do, it will most probably just be a workaroud or hack which is not a good way to go as it will come with one or more downsides. The only proper way that I see would be that `Bokeh` supports gaps in time axis natively.

**Comment by verybadsoldier** [comment]
I gave the method from my last post a try. You can find it in the develop branch. Feel free to test it out :)

Would be great if you could look for unwanted side effects and label errors.

**Comment by paduel** [comment]
That was great! Thanks for your interest and work.

I made a quick test and I found that the candles plot out of the window when I zoomed. Here you can see:

![test backtrader plotting 1](https://user-images.githubusercontent.com/5903320/36376333-0be6015e-1573-11e8-81ea-faa6dd4540f5.png)

**Comment by verybadsoldier** [comment]
As far as I can see that is a known Bokeh issue:
https://github.com/bokeh/bokeh/issues/6435

I will close this issue for now as I consider the date gaps fixed for now. Feel free to reopen if needed. Thank you!
