### ISSUE TITLE
Unable to plot hourly ticks

### ISSUE THREAD

**Issue by renheren** [verybadsoldier/backtrader_plotting#34]
![Screenshot_20191213_181002](https://user-images.githubusercontent.com/45765099/70792558-71ef4580-1dd4-11ea-8995-13660b0fcdc0.png)
It seems the result of hourly plotting is aligned to daily. While the plotting with matplotlib backend is correct.

**Comment by verybadsoldier** [comment]
I cannot reproduce and I am not sure what the problem is. Please provide full runnable example.

**Comment by verybadsoldier** [comment]
No further information provided
