### ISSUE TITLE
Can we customise the height of the plotted indicators?

### ISSUE THREAD

**Issue by JIACCOPU-ford** [verybadsoldier/backtrader_plotting#37]
This is what my indicator looks like. This is aprox 500px height. Can we customise the height with the existing api?

<img width="1567" alt="Screenshot 2020-02-21 at 17 28 28" src="https://user-images.githubusercontent.com/37177144/75056912-d4994780-54cf-11ea-9e42-8374fd7f4b35.png">

**Comment by verybadsoldier** [comment]
Yes, you can modify the height using the `plot_aspect_ratio` parameter. You can assign the value also only for specific plots: https://github.com/verybadsoldier/backtrader_plotting/wiki#plot-configuration

**Comment by JIACCOPU-ford** [comment]
I tried the suggested approach. it didn't  work. What am I doing wrong?

![Screenshot 2020-02-22 at 15 26 54](https://user-images.githubusercontent.com/37177144/75095001-61074100-5588-11ea-9dc2-41d8506dff7a.png)
![Screenshot 2020-02-22 at 15 32 28](https://user-images.githubusercontent.com/37177144/75095021-93b13980-5588-11ea-82c4-3545e9d7d586.png)

I tried setting it in the scheme only, and it worked fine, but it applied it to all elements, not just one indicator.

![Screenshot 2020-02-22 at 15 34 07](https://user-images.githubusercontent.com/37177144/75095043-c9eeb900-5588-11ea-8d27-b7ae8952ec82.png)

What do you suggest? Thanks.

**Comment by verybadsoldier** [comment]
You usually should pass `plotid` as part of the regular constructor arguments. I don't know `.real.plotid`.

If it is still not working then please provide a full example so I can look into it.

**Comment by JIACCOPU-ford** [comment]
I have set plotid as you recommended in the plotinfo dictionary (not in real) and your code picks it up okay, but unfortunately it makes no effect in the chart:
My code:

![Screenshot 2020-02-22 at 17 03 55](https://user-images.githubusercontent.com/37177144/75096217-5901ce00-5595-11ea-8296-6e418d3e882c.png)
![Screenshot 2020-02-22 at 17 03 20](https://user-images.githubusercontent.com/37177144/75096218-5c955500-5595-11ea-80c0-2bc73d06b2ed.png)

Your code does pick up the the plotid okay:

![Screenshot 2020-02-22 at 16 57 52](https://user-images.githubusercontent.com/37177144/75096225-6919ad80-5595-11ea-88bf-570d4f2a8894.png)

Unfortunately I get the same result and the indicator has the same aspect ratio. The following is an example I've tested using backtrader indicators (not talib). The problem is very easy to reproduce
[BokehTest.txt](https://github.com/verybadsoldier/backtrader_plotting/files/4239681/BokehTest.txt)

**Comment by verybadsoldier** [comment]
Sorry, I found the problem. There are actually two parameters for aspect ratio: `plotaspectratio` and `plot_aspect_ratio`. This was not intended.
Workaround for now is to set *both*. I will fix it in `develop` and only use `plotaspectratio` as introduced by backtrader.

**Comment by JIACCOPU-ford** [comment]
plotaspectratio worked as expected, thanks

**Comment by verybadsoldier** [comment]
One more thing to add for a possible reader in the future:
Parameter `plotid` is not known to vanilla backtrader so you cannot use it in the constructor (I suggested that above) as backtrader would complain about an unknown parameter.

So either use my backtrader branch (it knows about `plotid`) or set `plotid` manually to `plotinfo`after creating the object as @JIACCOPU-ford did correctly above.

**Comment by verybadsoldier** [comment]
> Workaround for now is to set _both_. I will fix it in `develop` and only use `plotaspectratio` as introduced by backtrader.

Well, I have to correct myself another time: backtrader never introduced ´plotaspectratio`. I just was not aware anymore that I added them in my fork just to be able to use them in constructor calls without problems.
