### ISSUE TITLE
Backtrader specifies plotname, but backtrader_plotting looks up plotid

### ISSUE THREAD

**Issue by JIACCOPU-ford** [verybadsoldier/backtrader_plotting#38]
When Backtraders talks about plotting, they talk about the `plotinfo` dictionary. One of the dictionary key is the `plotname` key. 

![Screenshot 2020-02-22 at 17 00 48](https://user-images.githubusercontent.com/37177144/75096904-2c04e980-559c-11ea-87ab-9bad73592b35.png)

Looking at the code in this repo, the way an object is identified for plotting reference is the `plotid` key in the infodictionary.

Since backtrader refers to its `plotinfo` name as `plotname`, wouldn't be better for this code to use `plotname` instead of `plotid` when trying to match an indicators?

https://github.com/verybadsoldier/backtrader_plotting/blob/87034bf4dc12ba70bafea9cf7aea0fd03cd1421c/backtrader_plotting/bokeh/bokeh.py#L119

**Comment by verybadsoldier** [comment]
I think `plotname`  is used to get a string suitable for displaying it to the user. But it is not a unique identifier. So it is perfectly fine to have multiple objects with the same `plotname`. But `plotid` should be unique and there should be no two objects having the same `plotid`. So it is meant to identify an object unambiguously.

**Comment by JIACCOPU-ford** [comment]
Okay. Is plotid a concept that you introduce, or is it a Backtrader thing?
If this is something that you introduce, we could add some documentation about it.

**Comment by verybadsoldier** [comment]
Yes, that is something I introduced for the purpose of identifying plot objects. It is mentioned in the documentation here: https://github.com/verybadsoldier/backtrader_plotting/wiki#plotting-options
