### ISSUE TITLE
Multiple timeframe error

### ISSUE THREAD

**Issue by JIACCOPU-ford** [verybadsoldier/backtrader_plotting#43]
Added two data resolutions, daily and weekly. It crashes when calling plo()

<img width="1561" alt="Screenshot 2020-03-14 at 18 51 31" src="https://user-images.githubusercontent.com/37177144/76688638-8e468c80-6626-11ea-9bcf-fb3c12130b18.png">

* Provide a minimal runnable source code example that shows the bug
`

      class SMAStrategy(bt.Strategy):
                

           def __init__(self):
                   self.sma_small_tf = btind.SMA(self.data, period=10)
                   self.sma_large_tf = btind.SMA(self.data1, period=10)

      data =  #one day candles
      data1 = #one week candles

      cerebro = bt.Cerebro()
      cerebro.adddata(data)
      cerebro.adddata(data1)
      cerebro.addstrategy(SMAStrategy)
      cerebro.run()
      b = Bokeh(style='bar', plot_mode='single', scheme=Tradimo())
      cerebro.plot(b)`

* Include the version of the library you are using (or the exact commit hash)
pip3 show: Version: 1.0.0

* Include version of your Python interpreter and of involved other libraries
Python 3.6

**Comment by verybadsoldier** [comment]
This is probably fixed in `develop` branch. You could check that.

If needed then please add the data part (preferably data included in backtrader) to your code example as this is crucial. Using different data than you did might lead to differing results.

**Comment by verybadsoldier** [comment]
Please reopen if issue is still present.
