### ISSUE TITLE
How to save optimization results as html file?

### ISSUE THREAD

**Issue by shiniantianlang** [verybadsoldier/backtrader_plotting#45]
when I close Plotting Optimization Results, the web doesn't work any more. So how can I can read the optimization results without running code again?

**Comment by verybadsoldier** [comment]
That is not in the scope of this project. The project can display a cerebro result in an interactive webapp. It is not relevant where this result comes from. In you case I would suggest to save your result to disk and load later (e.g. pickle).

**Comment by shiniantianlang** [comment]
Got it! Thank you very much!
