### ISSUE TITLE
Infinity Loop

### ISSUE THREAD

**Issue by lefig** [verybadsoldier/backtrader_plotting#46]
Hi there,

I have what looks like an infinity loop problem. 

The strategy has two datas and no trades were made.

I call:
b = Bokeh(style='bar', plot_mode='single')
self.cerebro.plot(b)

Then nothing seems to happen. I have high CPU of 30% and checked that some work is being done in the background. It is. In gave it 15 minutes but still no plot. Weird.

I would appreciate any kind suggestions.

Fig

**Comment by verybadsoldier** [comment]
Please provide full runnable sources to reproduce.

**Comment by lefig** [comment]
We are running Python 3.6 on Windows 10.

**Comment by verybadsoldier** [comment]
I meant runnable Python code. Please add a full example.

**Comment by lefig** [comment]
I see. Understood thank you in advance...

The plot function appears right at the bottom:

class Mean_Reversion(Abstract_Strategy):

    def __init__(self, config):
        super(Mean_Reversion, self).__init__()
        # Variable for our starting cash
        self.startcash = 10000
        self.config = config
        print ("Using:",matplotlib.get_backend())
        #Create an instance of cerebro
        self.cerebro = bt.Cerebro(stdstats=config['backtrader']['stdstats']) # std observers
        self.cerebro.broker.set_coc(True)
        self.execute_session()

    def create_engine(self):
        super(Mean_Reversion, self).initialise_engine(self.config)
        # Add strategy
        max_stocks = self.config['parameters']['mean_reversion']['max_stocks']
        self.cerebro.addstrategy(CrossSectionalMR, n=max_stocks)
       
        #Add our data
        super(Mean_Reversion, self).load_session_data()

        # Add analyzers
        self.cerebro.addobserver(bt.observers.Value)
        self.cerebro.addanalyzer(bt.analyzers.SharpeRatio, riskfreerate=0.0)
        self.cerebro.addanalyzer(bt.analyzers.Returns)
        self.cerebro.addanalyzer(bt.analyzers.DrawDown)

    def run_strategy(self):
        print('\nStarting Strategy')
        print('-'*80)
        # Run over everything
        results = self.cerebro.run()
        print(f"Sharpe: {results[0].analyzers.sharperatio.get_analysis()['sharperatio']:.3f}")
        print(f"Norm. Annual Return: {results[0].analyzers.returns.get_analysis()['rnorm100']:.2f}%")
        print(f"Max Drawdown: {results[0].analyzers.drawdown.get_analysis()['max']['drawdown']:.2f}%")
        
    def plot_analysis(self):
        #Finally plot the end results
        # If I have a lot of data feeds, it might be worthwhile to turn plotting off altogether.
        if self.settings['plot'] == True:
            if self.settings['plot_style'] == "bokeh":
                b = Bokeh(style='bar', plot_mode='single')
                self.cerebro.plot(b)
            else:
                self.cerebro.plot(style='candlestick', height=1000)

**Comment by lefig** [comment]
Just to add that I am running win 10 and backtrader as source files rather than an egg installed package.   And Bokeh 2.0.2. Thank you

**Comment by verybadsoldier** [comment]
I am sorry but I think this is neither complete nor runnable. At least I don't know how I could run this. I will close this for now but please feel free to reopen if you have something that let me reproduce the problem.
