### ISSUE TITLE
AttributeError: 'LineOwnOperation' object has no attribute 'size'

### ISSUE THREAD

**Issue by tylercollins590** [verybadsoldier/backtrader_plotting#47]
I am running into an issue when I am calculating a Standard Deviation Indicator from backtrader. I am setting plot=False for the indicator as I do not want to plot it.

I am receiving the following error:

> AttributeError: 'LineOwnOperation' object has no attribute 'size'

Here is my code for the indicator:
`b = bt.indicators.StandardDeviation(bt.If(-a > -a(-1), -a, 0), period=2, plot=False)`

**Comment by verybadsoldier** [comment]
Please provide full runnable code to reproduce.

**Comment by verybadsoldier** [comment]
Probably duplicate of #49
