### ISSUE TITLE
Panel disappear

### ISSUE THREAD

**Issue by tulliotech** [verybadsoldier/backtrader_plotting#48]
Hello
I'm a happy user of your library.
Unfortunately, when i put two indicators in the code, the panel with the wheel disappear and the page becomes larger than the screen. 
Can you help me?

'''
import datetime
import backtrader as bt
from backtrader_plotting import Bokeh
class TestStrategy(bt.Strategy):
params = (
('buydate', 21),
('holdtime', 6),
)
def next(self):
if len(self.data) == self.p.buydate:
self.buy(self.datas[0], size=None)
if len(self.data) == self.p.buydate + self.p.holdtime:
self.sell(self.datas[0], size=None)
if name == 'main':
cerebro = bt.Cerebro()
cerebro.addstrategy(TestStrategy, buydate=3)
cerebro.addanalyzer(bt.analyzers.TradeAnalyzer, _name='tradeanalyzer')
cerebro.addanalyzer(bt.analyzers.PyFolio, _name='pyfolio')
data = bt.feeds.YahooFinanceCSVData(
dataname="orcl-1995-2014.txt",

fromdate=datetime.datetime(2000, 1, 1),

todate=datetime.datetime(2001, 2, 28),
reverse=False,
)
cerebro.adddata(data)
cerebro.run()
b = Bokeh(style='bar', plot_mode='single')
cerebro.plot(b)
'''

**Comment by verybadsoldier** [comment]
You mean this, right?
![image](https://user-images.githubusercontent.com/364469/81602634-3c737600-93cd-11ea-8903-7ba2d40c3279.png)

Yeah I know the problem. Happens since some upgrade of Bokeh. No fix available yet, though, sorry.

**Comment by tulliotech** [comment]
Hello

thank you for your reply

I mean this



Il giorno lun 11 mag 2020 alle ore 21:21 verybadsoldier <
notifications@github.com> ha scritto:

**Comment by cryptorevizor** [comment]
> You mean this, right?
> ![image](https://user-images.githubusercontent.com/364469/81602634-3c737600-93cd-11ea-8903-7ba2d40c3279.png)
> 
> Yeah I know the problem. Happens since some upgrade of Bokeh. No fix available yet, though, sorry.

I am sorry, do you know how to fix it?

**Comment by verybadsoldier** [comment]
Sorry, no fix it available yet and I have no idea currently (didn't had time to investigate also). Probably somehow related to Bokeh's layout system. Maybe even just a Bokeh bug so maybe updating Bokeh might help at some point.

**Comment by happydasch** [comment]
this issue is fixed in btplotting: https://github.com/happydasch/btplotting. you could give it a try, but keep in mind, backtrader_plotting is upstream and btplotting is mainly intended for live plotting.

**Comment by verybadsoldier** [comment]
This is a Bokeh bug actually.

**Comment by happydasch** [comment]
Basically yes, the issue happens, because the tab which has the widest content defines the width. I have added an workaround for this in my code:

* removeable tabs
* stretch_width for columns in analyzer
* titles for analyzer entries are responsive

in backtrader_plotting, the analyzer tab is generating this problem, since it has a fixed column width (or so i remember).

only on the Pre Element, stretch_width has no effect, but you can remove the tabs you don't need. Also source code is a new tab there. So you can just add the analyzer or other tabs and leave the source code tab out.

**Comment by verybadsoldier** [comment]
> in backtrader_plotting, the analyzer tab is generating this problem, since it has a fixed column width (or so i remember).

Sorry but no, that is not correct: it happens also for auto-width columns. It is a general flaw in Bokeh's layout handling. It also happens in btplotting.

**Comment by happydasch** [comment]
you can compare the attached plots, one plotted using btplotting without source code, one plotted using btplotting with source code, one plotted with backtrader_plotting.

[Archiv.zip](https://github.com/verybadsoldier/backtrader_plotting/files/5136180/Archiv.zip)

**Comment by cryptorevizor** [comment]
Hi, maybe, i found the part of this problem.
In my strategy code I had a long line of code, something like this:
`if self.position.size > 0 and self.position.size > 0 and self.position.size > 0 and self.position.size > 0 and self.position.size > 0 and self.position.size > 0 and self.position.size > 0 and self.position.size > 0 and self.position.size > 0 and self.position.size > 0 and self.position.size > 0 and self.position.size > 0 and self.position.size > 0 and self.position.size > 0 and`
and due this tabs "source code" just crashes all html file
![Screenshot_2](https://user-images.githubusercontent.com/45230803/93210456-4f75c880-f768-11ea-904f-68d8187ee413.png)

after i styled my strategy code i got the correct display of the toolbar.  BINGO :)

**Comment by verybadsoldier** [comment]
I think there might be confusion about the issue we are talking about here. At least on my end. I posted a screenshot above and I assume that this is the problem here.
Let me just close this ticket. Feel free to open a new one if needed with a description of your problem.
