### ISSUE TITLE
AttributeError: 'LinesOperation' object has no attribute 'size'

### ISSUE THREAD

**Issue by FrankyLifts** [verybadsoldier/backtrader_plotting#50]
When trying out your simple plot sript on my code inside a jupyter notebook, I get error message:
'AttributeError: 'LinesOperation' object has no attribute 'size''

Here's the traceback:
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-4-aa56ec16d375> in <module>
    273 #cerebro.plot(height=30,iplot=True)
    274 b = Bokeh(style='bar', plot_mode='single')
--> 275 cerebro.plot(b)

E:\WPy64-3830\python-3.8.3.amd64\lib\site-packages\backtrader\cerebro.py in plot(self, plotter, numfigs, iplot, start, end, width, height, dpi, tight, use, **kwargs)
    987         for stratlist in self.runstrats:
    988             for si, strat in enumerate(stratlist):
--> 989                 rfig = plotter.plot(strat, figid=si * 100,
    990                                     numfigs=numfigs, iplot=iplot,
    991                                     start=start, end=end, use=use)

E:\WPy64-3830\python-3.8.3.amd64\lib\site-packages\backtrader_plotting\bokeh\bokeh.py in plot(self, obj, figid, numfigs, iplot, start, end, use, fill_data, tradingdomain, **kwargs)
    509             self._blueprint_strategy(obj, start, end, tradingdomain, **kwargs)
    510             if fill_data:
--> 511                 df: pd.DataFrame = self.build_strategy_data(obj, start, end)
    512 
    513                 new_cds = ColumnDataSource.from_df(df)

E:\WPy64-3830\python-3.8.3.amd64\lib\site-packages\backtrader_plotting\bokeh\bokeh.py in build_strategy_data(self, strategy, start, end, num_back, startidx)
    471 
    472         for obj in itertools.chain(strategy.getindicators(), strategy.getobservers()):
--> 473             for lineidx in range(obj.size()):
    474                 line = obj.lines[lineidx]
    475                 source_id = FigureEnvelope._source_id(line)

**Comment by verybadsoldier** [comment]
Please provide the information as requested in the issue template. Primarly a runnable example to reproduce the problem. Let me add that I won't be able to help with problems regarding jupyter.
