### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by happydasch** [verybadsoldier/backtrader_plotting#55]
I went through your code and I liked it

I did see some small issues I try to explain:

* when checking for data, check for AbstractDataBase not DataBase since clones (and feeds?) don't extend from DataBase

* when generating data, don't use strategy clock, instead use the data with lowest timeframe. Its because the strategies clock may be different than the lowest data source available. For example in oanda, the source data feed produces ticks, so even if no data is using ticks, the strategy clock will contain them. Now when checking for replay using this clock you will not be able to see if the data feed to plot did advance or not. So instead of using strategy.datetime... you would look for a data source with lowest timeframe and use this instead. Now everything will be based on the smallest feed to plot. Hopefully you can understand my point. 

for example this way:
```
def get_strategy_clock(strategy: bt.Strategy):
    data = None
    for d in strategy.datas:
        if (data is None
            or (d._timeframe < data._timeframe)
            or (d._timeframe == data._timeframe
                and d._compression < data._compression)):
            data = d
    return data
```

* When logging output from the client, don't use info but debug instead. If others are doing the same as me, then people will log strategy output using logging. I log strategy output with log level info and some additional info I log with log level debug to console. So the logging mixed into my strategy logs.

This points are just some suggestions for you, but don't feel the need to change them. This were just some personal things I noticed.

**Comment by verybadsoldier** [comment]
1. In almost all cases this is already the case as far as I can see. I found a single occurance where `DataBase` instead of `AbastractDataBase` is used. Are you about that?

2. I am not happy about the clock handling either and I am considering alternatives. There are alot of scenarios that have to be considered. Would be great if you could provide code demos that demonstrate the problems you have in mind.
I think your example would lead to problems when using different compressions that do not share the same base. E.g. compression `3` and `7`.
I like your idea from the other issue to also take the trading domain into account. Let's see...

3. I think you could configure each logger with different log levels as you wish to solve your problems. Not sure if I understood your problem correctly though.

**Comment by happydasch** [comment]
For
1. this could be, I just saw it where it prevented to plot one data feed
3. also possible, I did not get into it that much, since I rewrote the code for my needs. I have not enough experience with the logger to use it probably I think

you saw the mess I created in your code. these were just some points I remembered.

For
2. I understand that point, since for backtesting you take everything into account, you would use the strategy clock, I missed that point since I use your code for live plotting. So if there is no trading domain, you need to use that clock, my mistake. I did not use backtrader_plotting that much for backtesting, I will use it mainly for live plotting.

For the live plotting, it makes more sense what i suggested, I believe, since the data handling is different. It is possible to change the datastore for the client, so you are more independent from the strategy itself (using trading domain). So the only thing that is missing, is having a different method than get_strategy_data, which only generates data for the given trading domain (also the handling of data in the listener).

I am currently rewriting the liveclient and listener for myself and moving the responsibility of data handling to the client, so you can switch the datasource per client. so the listener just notifies the clients of new data, when next is called. after that every client will be able to fetch the data needed for the trading domain using the clock of the data feed, I hope. 

Just wanted you to know that stuff, maybe you can use some of that in backtrader_plotting. I'll close that issue now and will comment here, when I finished the code.

**Comment by verybadsoldier** [comment]
Ok, thank you. I appreciate your input. Surely some interesting aspects to keep in mind when trying to improve the clock handling. I have no final good plan yet.

**Comment by verybadsoldier** [comment]
Hell, I just realized how buggy the current clock implementation really ist, e.g. when using 2 datas using 18 and 7 compression like in this example. As a solution I think the smallest common divisor has to be calculated and the be used as common time base...
```
#!/usr/bin/env python
# -*- coding: utf-8; py-indent-offset:4 -*-
from __future__ import (absolute_import, division, print_function,
                        unicode_literals)

import datetime
import logging

import backtrader as bt

from backtrader_plotting.schemes import Blackly

try:
    from backtrader_plotting.bokeh.live.plotlistener import PlotListener
except AttributeError:
    raise Exception('Plotting in live mode only supported when using modified backtrader package from this branch https://github.com/verybadsoldier/backtrader/tree/development')

_logger = logging.getLogger(__name__)


class LiveDemoStrategy(bt.Strategy):
    params = (
        ('modbuy', 2),
        ('modsell', 3),
    )

    def __init__(self):
        pass
        #self._sma = bt.indicators.SMA(self.data0.close, subplot=True)
        #self._sma2 = bt.indicators.SMA(self.data1.close, subplot=True)

    def next(self):
        pos = len(self.data)
        if pos % self.p.modbuy == 0:
            if self.broker.getposition(self.datas[0]).size == 0:
                self.buy(self.datas[0], size=None)

        if pos % self.p.modsell == 0:
            if self.broker.getposition(self.datas[0]).size > 0:
                self.sell(self.datas[0], size=None)


def _get_trading_calendar(open_hour, close_hour, close_minute):
    cal = bt.TradingCalendar(open=datetime.time(hour=open_hour), close=datetime.time(hour=close_hour, minute=close_minute))
    return cal


def _run_resampler(data_timeframe,
                   data_compression,
                   resample_timeframe,
                   resample_compression,
                   runtime_seconds=27,
                   starting_value=200,
                   tick_interval=datetime.timedelta(seconds=11),
                   num_gen_bars=None,
                   start_delays=None,
                   num_data=1,
                   ) -> bt.Strategy:
    _logger.info("Constructing Cerebro")
    cerebro = bt.Cerebro()
    cerebro.addstrategy(LiveDemoStrategy)

    cerebro.addlistener(bt.listeners.RecorderListener)

    cerebro.addlistener(PlotListener, volume=False, scheme=Blackly(hovertool_timeformat='%F %R:%S', tabs='multi'), lookback=120)

    cerebro.addanalyzer(bt.analyzers.TradeAnalyzer)

    if not isinstance(resample_compression, list):
        resample_compression = [resample_compression]

    for i in range(0, num_data):
        start_delay = 0
        if start_delays is not None and i <= len(start_delays) and start_delays[i] is not None:
            start_delay = start_delays[i]

        num_gen_bar = 0
        if num_gen_bars is not None and i <= len(num_gen_bars) and num_gen_bars[i] is not None:
            num_gen_bar = num_gen_bars[i]

        data = bt.feeds.FakeFeed(timeframe=data_timeframe,
                                 compression=data_compression,
                                 run_duration=datetime.timedelta(seconds=runtime_seconds),
                                 starting_value=starting_value,
                                 tick_interval=tick_interval,
                                 live=True,
                                 num_gen_bars=num_gen_bar,
                                 start_delay=start_delay,
                                 name=f'data{i}',
                                 tradingdomain='sdf',
                                 )

        cerebro.resampledata(data, timeframe=resample_timeframe, compression=resample_compression[i])

    # return the recorded bars attribute from the first strategy
    res = cerebro.run()
    return cerebro, res[0]


if __name__ == '__main__':
    logging.basicConfig(format='%(asctime)s %(name)s:%(levelname)s:%(message)s', level=logging.DEBUG)
    cerebro, strat = _run_resampler(data_timeframe=bt.TimeFrame.Ticks,
                                    data_compression=1,
                                    resample_timeframe=bt.TimeFrame.Seconds,
                                    resample_compression=[18, 7],
                                    runtime_seconds=60000,
                                    tick_interval=datetime.timedelta(seconds=1),
                                    start_delays=[None, None],
                                    num_gen_bars=[0, 0],
                                    num_data=2,
                                    )

```

**Comment by happydasch** [comment]
So with your values of 7 sec (data0), 18sec (data1) the index will not align. basically the common index is 1sec. after 7 seconds the first candle is done, after 14 sec the next, then 18 sec data1 advances.

so for backtesting, currently it will just fill the gaps with the building candle, sec1 - candle, sec2 - candle, sec3 - candle ... sec7 candle finished (7 were plotted) the same goes for 18 sec. when using 1 sec clock (since you align the plots in backtest, they need to have the same index, there is no datetime index to align to).

so for backtesting, this is just fine, the only thing that would need attention, when creating the data is to update the correct candle. so even if the strategy clock advances, the different data feeds may not advance.

ok, so lets think what will when be updated. 

data0 advances -> new candle is starting at current position (strategy clock did advance for 7) - this sets the position of current candle based on strategy clock
data0 does not advance -> current candle (at the strategy clock position, where the candle was started) and all ind + obs, which have data0 as the clock need to update at the pos of current candle

the same for data1, then they are aligned at the correct index, no additional candles are being created.

in the above scenario, you would need to know when strategy clock advances, the lengths of all data feeds at last candle. also which ind and obs is using what data feed (or what clock they are using). so ind + obs are not very interesting, just the data feeds.

so even for resampledata, this should work the same, the only difference is, that there will be no data between data advances. (next will not be called until the candle advances)

so now for live plot


since you just show one trading domain (one data feed) -> it would be ok to just care for the data feed and the corresponding ind + obs (all other stuff is not being shown -> liveclient is calling _refreshmodel -> here it is possible to just fetch the data to show using the clock of the data domain) -> so for data0 the clock is advancing every 7 seconds, when new data arrives before data0 did advance, the current candle is being patched. -> here you just need to watch for the len of current data.


I hope, you can understand a bit what my thoughts about that are.

**Comment by happydasch** [comment]
ok, for the resample part, I am not sure, how the strategy clock will behave or how they would align correctly.

**Comment by happydasch** [comment]
hm, but you could also use a common self defined index with the lowest timeframe + compression that will align

**Comment by happydasch** [comment]
I mean, you just care for the data to be plot. they need to align, so with 7 and 18 sec the lowest index would be 1 (basically every time when new data arrives in next), for 5 sec and 10 sec the lowest index would be 5. so with the odd numbers, this is just a theoretical possibility since most will use 1,5,15,30,60,240 etc values which will align to the lowest timeframe. then the strategy clock is not important but just the data feeds, which are being plotted. you just watch if data feed advances, not when the strategy clock advances.

**Comment by happydasch** [comment]
ok, some thoughts were wrong above, since you cannot assume that you will get ticks regularly, hm, so yeah, maybe just looking for the lengths, taking the lowest data feed, using this as base, advance index of data in backtrader plotting, when this feed advances, advance others, when length of the data feeds changes, without taking too much into consideration. -> plot when data advances, until then, even if next is being called, just update the candle at the stored position. this is needed when showing all feeds, when using data domain, just use the clock of the feed to show.

**Comment by happydasch** [comment]
so in this case, using 7 and 18 secs, the positions will be candle 1-data0: 7 sec, candle 2-data0: 14 sec. candle 1-data1 for 18 sec at pos candle2-data0

**Comment by happydasch** [comment]
Other possibilities would be reconstructing the index from time, which may be a overkill? So with time you would know what time passed, what the common timeframe and compression is and being able to recreate the index correctly

**Comment by happydasch** [comment]
so with the time as a helper, you would advance based time between candles / common base:

7sec/common base 1sec -> advance index by 7 from last candle position, set times and index for empty rows (if any)
18sec/common base 1sec -> advance index by 18 from last candle position, set times for the empty rows (if any)

5min/common base 5min -> advance index by 1 from last candle
60min/common base 5min -> advance index by 12 from last candle, set times for empty rows (if any -> in that case no empty rows)

**Comment by verybadsoldier** [comment]
I am sorry, I am not sure if I could follow your thoughts entirely. But I can say that I missed one important fact yesterday: the time axis is not equidistant. This is important. So one data with daily bars should skip the weekend and therefore not show saturday and sunday. Yesteday for a reason I lived under the impression that the time axis should reflect gaps properly.

Keeping that in mind then the above code procudes perfectly correct plots imo. The strategy clock is basically exactly that: it contains a data for every timepoint at which one of the associated datas has a bar. It is ok that the time difference between points on the stratclock is not always identical.

So there are still problems using the strategy as clock but currently I think the best "master" clock would be a clockline that is basically a merge of all other clock lines (datas, indicators, observers).

Maybe somethin like this (easier to show code than trying to explain):
```python
    @staticmethod
    def _build_master_clock(strategy: bt.Strategy,
                            start: Optional[datetime.datetime] = None, end: Optional[datetime.datetime] = None,
                            num_back: Optional[int] = None,
                            startidx: int = 0):
        master_clock = []
        for obj in itertools.chain(strategy.datas, strategy.getindicators(), strategy.getobservers()):
            line_clk = get_clock_line(obj).plotrange(start, end)
            master_clock += line_clk

        # remove duplicates
        master_clock = list(dict.fromkeys(master_clock))

        master_clock.sort()

        master_clock = [bt.num2date(x) for x in master_clock]

        return master_clock
```

I might possibly realize that it also won't work later...

The master clock is to plotted then. Every item on the master clock will have data on at least one of the figures.

**Comment by happydasch** [comment]
Yeah, i understand the stuff is confusing I wrote yesterday. This were thoughts without spending any thoughts on that. For the gaps, your thoughts are not entirely correct. Based on the plot, you are correct, the conversion from dt to int index is needed to remove that kind of gaps. For the data feeds, it is not. based on the strategy clock, having for example 2 feeds: one has 5 min data, the other has 60 minutes. So there are gaps in the 60min feed compared to 5min. the 60min candle will be every 12 5min candles. 

> The strategy clock is basically exactly that: it contains a data for every timepoint at which one of the associated datas has a bar. It is ok that the time difference between points on the stratclock is not always identical.

Yes, that is correct, but somewhere in the current code, something is not working the way it should.

Also keep in mind, that ind and obs for a single trading domain will just contain timepoints based on the data feed. So the stratclock (or in most cases it is the data feed with lowest timeframe) is needed when you plot everything, but you get a better view, when using trading domain and the corresponding clock of the data feed, that is shown.

So when you take the replay data, it is generating the candles incorrect. Also backtest does not plot the second data feed correctly. I currently look into the get_start_end method, also the usage of plotrange, since the int numbers most probably will not match the lengths of the different data feeds (start, end will match the length of strategy clock, but not the different data feeds (I am not fully sure yet)-> this leads also to wrong data from plotrange (plotrange on lines takes a slice from a line array). Will know for sure, when I finished the current work. 

I worked today on a solution, I will commit this tomorrow, so you can see some code. That will explain it better. But like you wrote, your current solution should work, there are just some issues. My main intend is just to remove the gaps, when using the liveclient and switching the trading domain and to prevent the replay data to be filled with candle forming data. some additional stuff I will add is moving forward and backward in live data. So for the clock, I wrote a clock class which will handle the correct slicing of data, for the liveclient I wrote a class which handles the data. The listener will just send a row using the correct tradingdomain when next is called to the client, everything else is then processed in the data handler. So every client will have an own data handler, this way the forward and backward will be possible.

**Comment by happydasch** [comment]
These are the main methods to generate the data: 

So in convert_by_line_clock, I believe, that it never should happen, that a line will not have a corresponding entry in in the clock, also the indention of the second else is wrong. 

Also the comparison of sc == v and then adding it to new line is somehow wrong, it should go the other way around, where the new_clock is thee base for new_line. so I think it should go this way: 

go through new_clk, check if line_clk eq new_clk, if yes, add it to new line, advance index for line and line_clk, else just add nan to new line. nothing more should be done? 

`
def convert_by_line_clock(line, line_clk, new_clk):
    """Takes a clock and generates an appropriate line with a value for each entry in clock. Values are taken from another line if the
    clock value in question is found in its line_clk. Otherwise NaN is used"""
    if new_clk is None:
        return line

    clk_offset = len(line_clk) - len(line)  # sometimes the clock has more data than the data line
    new_line = []
    next_start_idx = 0
    for sc in new_clk:
        for i in range(next_start_idx, len(line_clk)):
            v = line_clk[i]
            if sc == v:
                # exact hit
                line_idx = i - clk_offset
                if line_idx < 0:
                    # data line is shorter so we don't have data
                    new_line.append(float('nan'))
                else:
                    new_line.append(line[line_idx])
                next_start_idx = i + 1
                break
        else:
            new_line.append(float('nan'))
    return new_line


def convert_to_pandas(strat_clk, obj: bt.LineSeries, start: datetime = None, end: datetime = None, name_prefix: str = "", num_back=None) -> pd.DataFrame:
    lines_clk = obj.lines.datetime.plotrange(start, end)

    df = pd.DataFrame()
    # iterate all lines
    for lineidx in range(obj.size()):
        line = obj.lines[lineidx]
        linealias = obj.lines._getlinealias(lineidx)
        if linealias == 'datetime':
            continue

        # get data limited to time range
        data = line.plotrange(start, end)

        ndata = convert_by_line_clock(data, lines_clk, strat_clk)

        df[name_prefix + linealias] = ndata

    df[name_prefix + 'datetime'] = [bt.num2date(x) for x in strat_clk]

    return df
`

**Comment by happydasch** [comment]
```
def convert_by_line_clock(line, line_clk, new_clk):
    """Takes a clock and generates an appropriate line with a value for each entry in clock. Values are taken from another line if the
    clock value in question is found in its line_clk. Otherwise NaN is used"""
    if new_clk is None:
        return line
    new_line = []
    c_idx = 0
    for sc in new_clk:
            v = line_clk[c_idx]
            if sc == v:
                    new_line.append(line[c_idx])
                c_idx += 1
            else:
                new_line.append(float('nan'))
    return new_line
```

**Comment by happydasch** [comment]
I added some backtest html files, so you can see the differences. The issues come with replay, I will need to look into that a bit deeper. But mostly it works now. It is strange, because replay has time values which are not in the strategies clock. also it was wrong to think that clock of data and data has the same lengths, sometimes the last value was missing. Will look into that, too. I have a suspicion why this is happening. 


I used backtrader_plotting from development branch and btplotting.

[Archiv.zip](https://github.com/verybadsoldier/backtrader_plotting/files/4869099/Archiv.zip)


Here you can also see, how backtrader is plotting replay and how it will be plotted in backtrader_plotting (look at the last candles and the gap before last candle):

Backtrader:
<img width="942" alt="Bildschirmfoto 2020-07-03 um 02 40 36" src="https://user-images.githubusercontent.com/4503314/86459107-99810d80-bd26-11ea-8033-3cbb70c37be7.png">

Backtrader_plotting:
<img width="635" alt="Bildschirmfoto 2020-07-03 um 02 41 08" src="https://user-images.githubusercontent.com/4503314/86459146-aa318380-bd26-11ea-890f-bb3c8e3bc998.png">

**Comment by happydasch** [comment]
Ok, i have mostly finished the data clock handling, you can see the relevant code here:

clock generator object:
https://github.com/happydasch/btplotting/blob/106fdc5321f054bf4702cba7e1af566ea17b382e/btplotting/app.py#L404

build_data (was build_strategy_data):
only this method should ever be called when generating data to plot.
https://github.com/happydasch/btplotting/blob/106fdc5321f054bf4702cba7e1af566ea17b382e/btplotting/app.py#L413

clock classes:
https://github.com/happydasch/btplotting/blob/btplotting/btplotting/helper/clock.py

this replaces all Bokeh._get_start_end(), convert_to_pandas(), convert_by_line_clock() etc. calls. It will work with tradingdomain (which I did not test yet, since in my version the liveclient is not runable atm.), it works on backtest. It also just creates the necessary clock arrays not for every object, but once and reuses them.

this is the relevant code to generate the clock arrays, which can later be used when creating the plot column for data, obs, ind 
https://github.com/happydasch/btplotting/blob/106fdc5321f054bf4702cba7e1af566ea17b382e/btplotting/app.py#L422-L448

So in your code, the usage of get_start_end, plotrange etc. was just for the strategy clock, but the lengths for obj, data, ind will be different. your code worked, since the strategy clock will always be either same or bigger than the size of the parts. 

https://github.com/happydasch/btplotting/tree/btplotting

i have changed the examples to use my class naming if you want to test it. 

If the changes are interesting for you, I can provide a PR for the data clock handling. Also I am not sure, how I could contribute back to your code, since I did a lot of refactoring, removed the opt browser for now, removed the dependency on the listener, removed the analyzer classes etc. maybe we can talk about that via email or other way, so we can use german.

**Comment by happydasch** [comment]
using live client, the different tradingdomains are now plotted without the gaps.


<img width="1318" alt="Bildschirmfoto 2020-07-03 um 21 01 17" src="https://user-images.githubusercontent.com/4503314/86493101-84c96780-bd70-11ea-9a22-09dc8bfb2695.png">
<img width="1318" alt="Bildschirmfoto 2020-07-03 um 21 01 32" src="https://user-images.githubusercontent.com/4503314/86493098-8004b380-bd70-11ea-8c3a-b20883ea3e8f.png">

**Comment by happydasch** [comment]
I have now also finished the liveclient (I will need to test the replay, since I changed the way it is defining the row to patch, it does not patch the datetime col anymore and I use the last datetime from the matching data). The next handling is way more simple now, basically it either adds or updates. Filling is done, when the datahandler is initialized. It never fetches more data than loopback. It goes faster now, since it just fetches the row in the listener and dispatches it to all clients using the right tradingdomain. in the client it is being processed by the datahandler. With that, I can now stop updating, so the scrolling in data should work. I have also fixed some introduced bugs in data handling and the markers in figure. 

It would be great to get feedback from you about the liveclient. I am not really sure, if I used the thread locks correctly there.

I will now put some work into plotting, I have to check, why the line sizes are not being applied and why the line style sometimes is wrong. After that I will update the analyzer and meta tab to be better formatted and in meta to use 2 cols, since the long height is making the whole page longer (there is also an bug #48 - the reason for this bug is the analyzer tab. I fixed that with #57 . The height and width of all tabs is defined by the biggest width and height of any tab, bokeh does not adapt the width and height of just the current tab).

**Comment by happydasch** [comment]
I believe, I also fixed all issues in last commit with patching by using index of source instead of dt. It will now look for the candle with the given index instead of using the dt. So now the dt can be changed. It is possible to exactly define, which row to patch with that.

**Comment by happydasch** [comment]
Alright, I have now tested backtesting and live. Everything works as expected. So I will stop posting in this issue now. Would be very happy to hear from you with some feedback about the code. Also the thread lock stuff. You can send me an email: daniel@vcard24.de.

What did I change:
-Added most markers from matplotlib (see PR #54)
-Added support for line width (see PR #54)
-Added support for replaydata in backtest and liveclient by changing the way the strategy clock is being used
-Added support for data generation using tradingdomain, so only data for that tradingdomain is being generated (no gaps in liveclient, gaps when plotting everything on a single page)
-Fixed usage of clock index using strategy clock, using tradingdomain clock
-Fixed issues in liveclient with dt by using the clock index instead
-Removed start_idx usage, using restoreidx instead (since now, it is always possible to know the position of the slice)
-Moved data responsibility to liveclient from listener (so the client can act independent from listener on data)
-Removed UpdateType.FILL since this will now done automatically in datahandler when it is created (only ADD / UPDATE is now being done)
-Cleaned up a lot of code

Most of this changes are compatible with your current code. So I can possibly add them if you like.

**Comment by verybadsoldier** [comment]
Ok, thank you. You did quite alot there in your branch. I guess I will be having a hard time to find my way through as it contains project restructures, refactors, bugfixes and features. Not sure if I will be going to merge the structural changes but I will surely merge some of the improvements (like the dynamic data tables). So thanks alot!

**Comment by happydasch** [comment]
I added optbrowser and the analyzer injection code yesterday, so now all functionality is in there, that is in your code. I also fixed the fixed size of the optbrowser there, now it is responsive. Everything except listener which is now an analyzer.

bokeh.py -> app.py (Bokeh -> BacktraderPlotting)
figureenvelope.py -> figure.py (I moved the FigurePage also in there)
 -> clock.py (the clock stuff to handle data)
 -> live/client.py (the live client is in there)
 -> live/datahandler.py (data handler for live data)
 -> analyzers/plot.py (the listener / analyzer for live plotting)
 -> analyzers/recorder.py (the recorder from modified backtrader)
 -> feeds/fakefeed.py (the fake feed from modified backtrader)

**Comment by happydasch** [comment]
Another update about the code in fork. It is now stable, so I will not change that much in there anymore.

Everything works, that was an issue like live plotting, missing lines, issues when patching lines in live client, missing markers, code cleanups and refactoring. A lot of bugs I introduced are gone.

I mostly looked for live plotting, so I did not put much thoughts about opt browser, but it is still in there. I cleaned up the bokeh model code in live client, moved panels from app (Bokeh), etc. there is a lot of improvements in there and the code is a bit smaller now. The metadata tab is using data tables now, no markdown, there is no source code anymore. there are now different aspect ratios for data, ind, obs and vol in scheme with config in liveclient.

i have also added a basic navigation to live client. so you can pause streaming and browse in existing data.

What I will add, when having some free time is:
-generate data based on figurepage and datadomain not based on strategy and datadomain
-reorder plot objects to match backtrader (obs, data, ind)
-reactivate pytest stuff, to work with fork
-other small issues (TODOs in code)
