### ISSUE TITLE
Minimal example isn't that

### ISSUE THREAD

**Issue by gshpychka** [verybadsoldier/backtrader_plotting#58]
The minimal example listed in the readme does not run, as it references an external file `datas/orcl-1995-2014.txt`, which does not exist on my machine.

**Comment by verybadsoldier** [comment]
That file is part of the standard backtrader data package and you can also find it in the folder `demos/datas` in this project.

**Comment by gshpychka** [comment]
You should consider changing the Minimal example to be an actual minimal example - a copy-pastable piece of code that is ready to run after installing the package.
