### ISSUE TITLE
Set plotinfo.plot=False, but will still plot the BuySell chart.

### ISSUE THREAD

**Issue by luoqygit** [verybadsoldier/backtrader_plotting#61]
I want to disable BuySell charts because I have too many of them (hundreds of data feeds).

In standard backtrader implementation, I simply need to do like this:

```python
for d in cerebro.datas:   
    d.plotinfo.plot = False

cerebro.plot()
```

But it doesn't work when using backtrader_plotting.  
To implement that, I have to do like this:

```python

# first I need to remove bt.observers.BuySell, which will be added by default
cerebro = bt.Cerebro(stdstats=False)
cerebro.addobserver(bt.observers.Broker)
cerebro.addobserver(bt.observers.Trades)

...

# then disable each data feed
for d in cerebro.datas:
    # plotname **MUST** be set otherwise it won't work neither
    d.plotinfo.plotname = d._name
    d.plotinfo.plot = False

# finally call plot
b = Bokeh(style="bar", scheme=Tradimo())
cerebro.plot(b)
```

My questions are:
1. Can I simply disable data feeds, without disabling bt.observers.BuySell, like in backtrader?
2. Why must I set plotinfo.plotname?

I am new to backtrader and backtrader_plotting, so I was probably wrong. I would appreciate it if someone can tell me my mistakes.  
Thanks and best regard.

**Comment by verybadsoldier** [comment]
Yeah when having the BuySell activate then it will also activate the data feed "through the backdoor" as it wants to plot on that.

You can fix it by replacing
```python
                    if plotmaster not in data_graph:
                        data_graph[plotmaster] = []
                    data_graph[plotmaster].append(obj)
```
by
```python
                if plotmaster.plotinfo.plot:
                    if plotmaster not in data_graph:
                        data_graph[plotmaster] = []
                    data_graph[plotmaster].append(obj)
```
in the code.

Sorry, I didn't quite understand the part of your question regarding the `plotname` though. If it is still an issue then please add a runnable example to show the problem.

**Comment by luoqygit** [comment]
> Yeah when having the BuySell activate then it will also activate the data feed "through the backdoor" as it wants to plot on that.
> 
> You can fix it by replacing
> 
> ```python
>                     if plotmaster not in data_graph:
>                         data_graph[plotmaster] = []
>                     data_graph[plotmaster].append(obj)
> ```
> 
> by
> 
> ```python
>                 if plotmaster.plotinfo.plot:
>                     if plotmaster not in data_graph:
>                         data_graph[plotmaster] = []
>                     data_graph[plotmaster].append(obj)
> ```
> 
> in the code.
> 
> Sorry, I didn't quite understand the part of your question regarding the `plotname` though. If it is still an issue then please add a runnable example to show the problem.

Thanks a lot!
It works after replacing the code in bokeh.py as you sugguested.
