### ISSUE TITLE
legends and headers of backtrader_plotting looks bad and cannot be removed

### ISSUE THREAD

**Issue by Jenabe-Masih** [verybadsoldier/backtrader_plotting#66]
Hi @verybadsoldier 
First and foremost, I'd like to thank you for your awesome job. 

As is seen from the picture that I uploaded, I don't know why but legends and headers of my plot look terrible.  I tried to disable legends by writing something like this, it did not work, even though it didn't return any error! 

`    b = Bokeh(style='bar', scheme=Tradimo(), plot_mode='single', legend=False)
    cerebro.plot(b)`

Secondly,  could you please tell me how can I can for example add a title to each axis of my plot?

![legends](https://user-images.githubusercontent.com/50525094/93338353-89a79e80-f82a-11ea-84c8-9e8a89fc9e46.PNG)

**Comment by verybadsoldier** [comment]
Please add information as asked for in the issue template.
