### ISSUE TITLE
clarification / enhancement on demos - how to add tabs

### ISSUE THREAD

**Issue by johndpope** [verybadsoldier/backtrader_plotting#8]
not sure how to do this but would be cool to see tabs. 

blackly_tabs

perhaps the python code to generate demo pages could be uploaded too? 

<img width="616" alt="screen shot 2018-04-07 at 16 04 10" src="https://user-images.githubusercontent.com/289994/38459858-576c8010-3a7d-11e8-8f75-2158f9f8e879.png">

**Comment by johndpope** [comment]
presumably manually crafted. would be good to know how to inject the indicators. 



found some code that's plotting macd using bokeh. 
https://github.com/TangoJP/technical_analysis
<img width="293" alt="screen shot 2018-04-07 at 16 38 26" src="https://user-images.githubusercontent.com/289994/38460123-25101406-3a82-11e8-9540-5bf03678dc28.png">

**Comment by verybadsoldier** [comment]
There are two different modes the plotting library can operate in: `tabs` and `single`. `tabs` is the default and all indicators you add to the `backtrader` mix will end up in the `Indicators` tab. Nothing to be done manually.

As you noticed already the Readme is outdated showing the old `enum` code:
```
b = Bokeh(style='bar', plot_mode=PlotMode.Single, scheme=Tradimo())
cerebro.plot(b)
```

This should now be:
```
b = Bokeh(style='bar', plot_mode='bars', scheme=Tradimo())
cerebro.plot(b)
```

`enum` was changed to `str` to be more in line with the other `backtrader` scheme attributes.

**Comment by johndpope** [comment]
Thanks

**Comment by johndpope** [comment]
this is mint. awesome job.
